Ugabuga my way into making the project work
cambiatus/hands-on-elixir-and-otp-cryptocurrency-trading-bot-source-code pull request #1
Opened 2022-09-09 19:58 UTC by lucca65

2022-09-12 13:35 UTC, NeoVier commented on config/config.exs
> +  exchange_client: Core.Exchange.Binance,
Será que seria melhor termos alguma variável que define o `exchange_client`, e sempre ter isso sincronizado nas configs do `:streamer` e do `:naive`? 

Como sempre vamos usar a binance, será que faz sentido termos os dados vindo de um lugar (por exemplo, com `binance_client: BinanceMock` no `:streamer`), e fazer trade em outro (por exemplo, com `exchange_client: Binance` no `:naive`)?

2022-09-12 13:40 UTC, MatheusBuss commented on config/config.exs
> +  exchange_client: Core.Exchange.Binance,
Eu acho que o contrário do teu exemplo faz sentido. Usar o streamer pra `Binance` e o trader pra `BinanceMock`. Dessa maneira podemos testar o trader em dados reais, mas usando o mock pro trader pra poder testar estratégias antes de implementar em um ambiente de produção.

Se bem que não tenho certeza de onde vêm os dados do `:streamer` pro `BinanceMock`, talvez ele sempre use dados reais? Tenho que pesquisar isso.

2022-09-12 13:51 UTC, NeoVier commented on config/config.exs
> +  exchange_client: Core.Exchange.Binance,
Parece que o `binance_client` do streamer só é usado pra fazer o seed do banco (no arquivo `apps/streamer/priv/seed_settings.exs`) - e mesmo assim, no fim das contas, ele só chama `Binance.get_exchange_info` (isso acontece em `apps/binance_mock/lib/binance_mock.ex`, na função `fetch_exchange_info`). Então parece que os dados vêm sempre da Binance de qualquer jeito.

O `BinanceMock` só oferece uma layer de cache ao redor do `Binance.get_exchange_info`, pra não ter que buscar todos esses dados todas as vezes que o app é iniciado (o que realmente é interessante em tempo de desenvolvimento, pq demora alguns segundos até pegar todos os dados da binance). Então realmente talvez faça sentido esse caso de usar o mock pro streamer

2022-09-12 14:46 UTC, lucca65 commented on config/config.exs
> +  exchange_client: Core.Exchange.Binance,
pensando a mais longo prazo, podemos ingerir dados de várias fontes, como por exemplo da Binance, da Coinex, da Kucoin e ainda sim só fazer trade em uma delas. Acho que é bom que tenhamos a diferenciação. Agora um ponto interessante que o @NeoVier trouxe é o uso dessas configurações. Pois tudo que vai na configuração tem a ver com setup ou até mesmo infra. 

Pra mim faz sentido que a ingestão de dados, trabalho do streamer seja mais dinâmico mesmo, ou seja, não faça parte  de configs.

Pro caso de seeding, acho que isso pode ser recebido como um parâmetro do script de sede, o que acham? Assim podemos rodar coisas como:

- `mix run priv/seeds --BinanceMock`
- `mix run priv/seeds --Binance`
- `mix run priv/seeds --BinanceFutures`

2022-09-12 14:51 UTC, lucca65 commented on config/config.exs
> +  exchange_client: Core.Exchange.Binance,
Oq acham?

2022-09-12 17:24 UTC, NeoVier commented on config/config.exs
> +  exchange_client: Core.Exchange.Binance,
+1, inclusive acho que esse parâmetro no arquivo de config ficou bem confuso do jeito que tá

2022-09-14 19:58 UTC, MatheusBuss commented
@lucca65 @NeoVier o bot deve estar funcionando agora. A única coisa que vai impedir que rode só com esse PR imagino que seja a dependência da Binance, mas de resto parece que está funcionando. Claramente ainda vamos ter coisas pra melhorar/arrumar, mas acho que pra um estado básico deve funcionar.

2022-09-15 13:58 UTC, MatheusBuss requested changes
Temos em mãos agora um bot funcionando (mesmo que me pareça que ele tem alguns erros ainda). Estudando o código ele me parece bem mais robusto do que tinha pensado que ia ser.

Já consegui adaptar par rodar nosso fork da binance, mas tive que fazer algumas mudanças locais nele. Por isso acho que seria bom tratarmos dos assuntos que eu comentei em https://github.com/cambiatus/binance.ex/pull/2 antes de avançar muito mais por aqui.

Ao mexerem no bot só vou deixar um aviso, em muitos lugares não há uma definição de erro muito boa, então não é tão comum ele apontar a origem do erro de cara. Uma sugestão que eu faço é adicionar mais `cases` e substituir as cláusulas dos `cases` existentes de `error -> error`, para `{:error, erorr} -> {:error, error}`. Assim se vier algum valor inesperado ele acusa no lugar certo.

2022-09-15 13:58 UTC, MatheusBuss commented on apps/streamer/lib/streamer/binance.ex
> +    )
@lucca65 pensei em fazer um check que se um processo com o nome de `"orders_streamer"` está rodando quando incializa um streamer. Dessa maneira mantemos essa stream dentro do módulo de streamers e, a princípio, garantimos que quando um streamer de um símbolo incializa ele também tenta incializar o streamer que dá update nas order.

O problema poderia ser o terminar um streamer de símbolo, que poderia levar o streamer de orders com ele. Não sei se teria um workaround ou seria melhor fazer o streamer de orders separado mesmo.

2022-09-15 13:58 UTC, MatheusBuss commented on apps/naive/lib/naive/strategy.ex
> +  defp status_to_atom("CANCELLED"), do: :cancelled
Não acho que seria bem o lugar dessas funções, mas não tenho muitas outras ideias pra manter esse "stack" de decisions e positions que já está implementado.

2022-09-15 13:58 UTC, MatheusBuss commented on apps/naive/lib/naive/strategy.ex
> +        )
Com a introdução de order events algumas variáveis não encaixaram muito bem o nome, como esse `trade_event` que na verdade agora corresponde a um `order_event` (destacado abaixo). Podemos ou separar esses caminhos em funções que aceitam `trade_event` e funções que aceitam `order_event` ou renomear simplesmente para `event`. Talvez a primeira opção seja mais fácil de seguir a lógica, mas acho que não vamos conseguir escapar de alguma duplicação de código. O que acham @NeoVier  @lucca65?
```suggestion
      :update_buy_position ->
        current_buy_order = update_order_position(position, :buy_order, order_event.order_status)

        generate_decisions(
          rest,
          [{:skip, %{position | buy_order: current_buy_order}}] ++ generated_results,
          trade_event,
          settings
        )

      :update_sell_position ->
        current_sell_order =
          update_order_position(position, :sell_order, order_event.order_status)

        generate_decisions(
          rest,
          [{:skip, %{position | sell_order: current_sell_order}}] ++ generated_results,
          order_event,
          settings
        )
```

2022-09-16 17:16 UTC, lucca65 commented
> existentes de `error → error`, para `{:error, erorr} -> {:error, error}`

Po, pelo menos é um erro honesto do cara que fez né? já mandei essa algumas vezes kkkkk

2022-09-16 17:18 UTC, lucca65 commented on apps/streamer/lib/streamer/binance.ex
> +    )
Acho que conseguimos fazer isso através de uma supervision tree. Logo mais você me explica melhor o que tá pensando e vemos como estruturar isso bem, mas parece que vai atender bem!

2022-09-16 17:20 UTC, lucca65 commented on apps/naive/lib/naive/strategy.ex
> +  defp status_to_atom("CANCELLED"), do: :cancelled
Fora do contexto geral tá um pouco difícil entender, mas acho que conseguimos fazer melhor, talvez manter o status/ position da ordem dentro de um estado de processo. Falamos mais logo menos

2022-09-19 18:17 UTC, NeoVier approved these changes
Foi mal pela demora!

Ainda temos alguns rough edges pra acertar, mas acho que pra começar a experimentar tá ótimo 🔥

2022-09-19 18:17 UTC, henriquecbuss commented on .credo.exs
> +# this after creating it with `mix credo.gen.config`.
Se vamos usar o credo, provavelmente deveríamos fazer o setup das Github Actions pra sempre rodar isso nos PRs

2022-09-19 18:17 UTC, henriquecbuss commented on apps/binance_mock/mix.exs
> +       ref: "667c6672022b5a9370b539f0ee64755cbb131d32"},
Podemos usar a master agora 🎉

2022-09-19 18:17 UTC, henriquecbuss commented on apps/naive/lib/naive/strategy.ex
> +        )
Talvez podemos ter um conjunto de funções que servem como base (que recebem um `event`), e criar outras funções mais especializadas (que recebem um `trade_event` ou `order_event`) que usam as funções base e adicionam o que for necessário, talvez operando em uma estrutura de dados genérica, que pode ser criada a partir de qualquer uma das estruturas mais específicas.

De qualquer forma, acho que as duas opções (receber só `event` ou duplicar um pouco de código) são válidas. Nessa fase mais exploratória, talvez valha a pena manter tudo como `order_event`, e podemos revisitar isso mais tarde

2022-09-19 18:17 UTC, henriquecbuss commented on apps/naive/lib/naive/strategy.ex
> +  defp status_to_atom("CANCELLED"), do: :cancelled
Também acho que isso não faz muito sentido aqui. Me parece que a única coisa desse módulo específico à estratégia `naive` é a parte de `generate_decision` (o que faz sentido). Não sei direito quais ferramentas o Elixir tem para isso, mas acho que seria legal termos uma forma de só especificar o `generate_decision`, e o resto ser tudo implementado pra gente (talvez um [behaviour](https://elixir-lang.org/getting-started/typespecs-and-behaviours.html#behaviours)?).

Assim fica bem mais fácil de criar novas estratégias. Podemos definir que o `generate_decision` conversa com o python, ou usa algum indicar em elixir mesmo, etc.

2022-09-22 12:56 UTC, MatheusBuss commented on .credo.exs
> +# this after creating it with `mix credo.gen.config`.
Com certeza, +1. Criei a issue #6.

2022-09-22 13:05 UTC, MatheusBuss commented on apps/naive/lib/naive/strategy.ex
> +  defp status_to_atom("CANCELLED"), do: :cancelled
Desculpa pela demora pessoal, estava experimentado com os scripts em Python. Acho que o que fica meio de fora aqui é a posição do código nesse arquivo, mas nesse arquivo em si ele deveria estar. Essa parte é resposável apenas por detectar quando uma order é atualizada, não envolve muito sobre a estratégia.

Digo que ele ficou meio fora do lugar por que o padrão é gerar a decisão dentro de um `generate_decision` e executá-la em um `execute_decision`. Nesse caso o `generate_decision` está normal, mas como é necessária a variável `order_decision` (que não é passada para o `execute_decision`) eu optei por fazer dessa maneira.

Mas acho que é algo que podemos rever posteriormente com calma, quem sabe até pegamos um dia pra discutir melhor o futuro do projeto e bater o martelo em algumas coisas.

2022-09-22 13:07 UTC, MatheusBuss commented on apps/naive/lib/naive/strategy.ex
> +        )
Também acho que é algo que podemos ver decidir mais para frente, quando tivermos um escopo mais global do projeto definido. Até porque talvez tenhamos que reecrever isso posteriormente de qualquer jeito

2022-09-22 13:07 UTC, MatheusBuss approved these changes

2022-09-22 13:11 UTC, MatheusBuss commented
@lucca65 @NeoVier acho que para um estado básico já está funcionando. Acho que podemos deixar algumas conversas sem serem resolvidas para termos um histórico de coisas que precisamos fazer.

Mas acredito que já podemos mergear essa pra ter um caminho base pros outros PR's, o que acham?

2022-09-22 13:38 UTC, NeoVier commented
Por mim podemos mergear. Como eu disse, ainda temos algumas coisas pra acertar, mas já tá ótimo para irmos experimentando

2022-09-26 00:45 UTC, merged

2022-09-26 00:45 UTC, lucca65 commented
Lets go!!! 💪